name: Alex Waibel
bio: A software engineer with a life-long passion for technology.
description: A blog about technology and stuff
external-image: false
picture: assets/images/profile.png
resume: true
resume-external: true
resume-url: 'https://github.com/alexwaibel/resume/blob/master/alex_waibel_resume.pdf'
url: 'https://alexwaibel.github.io'
permalink: '/:title/'
disqus:
  shortname: mydisqus
  categories: []
twitter: thealexwaibel
instagram: thealexwaibel
linkedin: alexwaibel
spotify: alex.waibel
github: alexwaibel
lastfm: alexwaibel
reddit: alexwaibel
email: alex@waibel.us
authors:
  alexwaibel:
    name: Alex Waibel
    bio: A software engineer with a life-long passion for technology.
    external-image: false
    picture: assets/images/profile.png
    twitter: thealexwaibel
width: large
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links:
  - blog
show-author: true
animation: true
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin
jekyll-mentions:
  base_url: 'https://github.com'
compress_html:
  ignore:
    envs:
      - development
      - stage
exclude:
  - travis.sh
  - Rakefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - FAQ.md
